services:
  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      PORT: 4000
    ports:
      - "0.0.0.0:4000:4000"

  discord-bot:
    build:
      context: ./discord-bot
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - ./discord-bot/.env
    environment:
      CHEKSSA_SERVER_URL: http://server:4000
